---
kind: pipeline
name: build master html

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_html.sh
  - ./publish_html.sh
  environment:
    DOC_BRANCH: master
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: master
    WEBSITE_RELEASE: master
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build master pdf

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_pdf.sh
  - ./publish_pdf.sh
  environment:
    DOC_BRANCH: master
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: master
    WEBSITE_RELEASE: master
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build master epub

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_epub.sh
  - ./publish_epub.sh
  environment:
    DOC_BRANCH: master
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: master
    WEBSITE_RELEASE: master
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build latest html

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_html.sh
  - ./publish_html.sh
  environment:
    BUILD_TYPE: latest
    DOC_BRANCH: v3000_docs
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 3000
    WEBSITE_RELEASE: latest
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build latest pdf

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_pdf.sh
  - ./publish_pdf.sh
  environment:
    BUILD_TYPE: latest
    DOC_BRANCH: v3000_docs
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 3000
    WEBSITE_RELEASE: latest
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build latest epub

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_epub.sh
  - ./publish_epub.sh
  environment:
    BUILD_TYPE: latest
    DOC_BRANCH: v3000_docs
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 3000
    WEBSITE_RELEASE: latest
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build 2019.2 html

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_html.sh
  - ./publish_html.sh
  environment:
    BUILD_TYPE: previous
    DOC_BRANCH: v2019.2.3_docs
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2019.2.3
    WEBSITE_RELEASE: 2019.2
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build 2019.2 pdf

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_pdf.sh
  - ./publish_pdf.sh
  environment:
    BUILD_TYPE: previous
    DOC_BRANCH: v2019.2.3_docs
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2019.2.3
    WEBSITE_RELEASE: 2019.2
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build 2019.2 epub

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_epub.sh
  - ./publish_epub.sh
  environment:
    BUILD_TYPE: previous
    DOC_BRANCH: v2019.2.3_docs
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2019.2.3
    WEBSITE_RELEASE: 2019.2
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

...
