---
kind: pipeline
name: build develop html

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_html.sh
  - ./publish_html.sh
  environment:
    DOC_BRANCH: develop
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: develop
    WEBSITE_RELEASE: develop
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build develop pdf

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_pdf.sh
  - ./publish_pdf.sh
  environment:
    DOC_BRANCH: develop
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: develop
    WEBSITE_RELEASE: develop
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build develop epub

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_epub.sh
  - ./publish_epub.sh
  environment:
    DOC_BRANCH: develop
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: develop
    WEBSITE_RELEASE: develop
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build latest html

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_html.sh
  - ./publish_html.sh
  environment:
    DOC_BRANCH: 2019.2.1
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2019.2.1
    WEBSITE_RELEASE: latest
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build latest pdf

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_pdf.sh
  - ./publish_pdf.sh
  environment:
    DOC_BRANCH: 2019.2.1
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2019.2.1
    WEBSITE_RELEASE: latest
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build latest epub

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_epub.sh
  - ./publish_epub.sh
  environment:
    DOC_BRANCH: 2019.2.1
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2019.2.1
    WEBSITE_RELEASE: latest
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build 2018.3 html

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_html.sh
  - ./publish_html.sh
  environment:
    DOC_BRANCH: 2018.3
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2018.3.4
    WEBSITE_RELEASE: 2018.3
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build 2018.3 pdf

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_pdf.sh
  - ./publish_pdf.sh
  environment:
    DOC_BRANCH: 2018.3
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2018.3.4
    WEBSITE_RELEASE: 2018.3
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

---
kind: pipeline
name: build 2018.3 epub

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ubuntu:bionic
  commands:
  - ./build_epub.sh
  - ./publish_epub.sh
  environment:
    DOC_BRANCH: 2018.3
    WEBSITE_PASSWORD:
      from_secret: website_password
    WEBSITE_POINT_RELEASE: 2018.3.4
    WEBSITE_RELEASE: 2018.3
    WEBSITE_USER:
      from_secret: website_user

trigger:
  event:
    exclude:
    - pull_request

...
