#!/bin/bash

salt-call state.apply builddocs pillar='{"version":"previous","publish":"false"}'
salt-call state.apply builddocs pillar='{"version":"latest","publish":"false"}'
salt-call state.apply builddocs pillar='{"version":"develop","publish":"false"}'
# salt-call state.apply builddocs pillar='{"version":"next","publish":"false"}'
salt-call state.apply builddocs.print pillar='{"version":"previous","publish":"false"}'
salt-call state.apply builddocs.print pillar='{"version":"latest","publish":"false"}'
salt-call state.apply builddocs.print pillar='{"version":"develop","publish":"false"}'
# salt-call state.apply builddocs.print pillar='{"version":"next","publish":"false"}'
