#!/bin/bash

salt-call state.apply builddocs.clean
salt-call state.apply builddocs pillar='{"version":"previous"}'
salt-call state.apply builddocs pillar='{"version":"latest"}'
salt-call state.apply builddocs pillar='{"version":"develop"}'
salt-call state.apply builddocs pillar='{"version":"next"}'
salt-call state.apply builddocs.print pillar='{"version":"previous"}'
salt-call state.apply builddocs.print pillar='{"version":"latest"}'
salt-call state.apply builddocs.print pillar='{"version":"next"}'
